### ISSUE TITLE
Typo in etc/cont-init.d/10-fusiondirectory

### ISSUE THREAD

**Issue by hongkongkiwi** [tiredofit/docker-fusiondirectory#16]
Hi there, looks like there is a typo in the init script.

```
fusiondirectory-app_1  | /var/run/s6/etc/cont-init.d/10-fusiondirectory: line 94: ENABLE_USER_REMINDER: "TRUE": syntax error: operand expected (error token is ""TRUE"")
```

When I look at line [94](https://github.com/tiredofit/docker-fusiondirectory/blob/master/install/etc/cont-init.d/10-fusiondirectory#L94), it's simply missing a `-` there. Currently, it reads:
```
ENABLE_USER_REMINDER=${ENABLE_USER_REMINDER:"TRUE"}
```

It should read:
```
ENABLE_USER_REMINDER=${ENABLE_USER_REMINDER:-"TRUE"}
```

**Comment by tiredofit** [comment]
Thanks for reporting. I've pushed a new tag `1.19.1` to github. Docker Hub will update it's `latest` and `1.19.1` tag shortly.
