### ISSUE TITLE
 nginx: [emerg] unknown log format "specialLog" in /etc/nginx/conf.d/default.conf:7

### ISSUE THREAD

**Issue by Anganthier** [tiredofit/docker-fusiondirectory#18]
2019-12-23: Used the example docker-compose.yml file to start the fusiondirectory-app. 

I am getting the above error while starting nginx. I guess it has something to to with the update of the base image a couple of days ago.

**Comment by tiredofit** [comment]
No problem, let me fix this up immediately.

**Comment by tiredofit** [comment]
I've just pushed tag 2.0.0 and :latest to Docker hub for building. Sorry about this, I had meant to update all images to support the new base image but missed out on this one.

**Comment by Anganthier** [comment]
Hi, thanks. Nginx is starting now.

Now I am missing the plugins like personal, dns or mail.

I am not sure if it's the same or a new one:
While starting I am gettting:
- chmod: /etc/php7/conf.d/00_bz2.ini: No such file or directory
...........
- [cont-init.d] 20-php-fpm: exited 0.
- [cont-init.d] 30-fusiondirectory: executing... 
- rm: can't remove '/assets/fusiondirectory-- plugins/applications/admin/applications': Directory not empty
.........
-** [fusiondirectory] Enabling the following plugins: alias, dns, ldapdump, ldapmanager, mail, personal, posix, sudo, webservice
- tar: ./fusiondirectory-plugins/applications/admin/applications/class_applicationGeneric.inc: No such file or directory
.....
- tar: error exit delayed from previous errors
- Can't write to {/www/fusiondirectory}/include/variables.inc: No such file or directory at /usr/sbin/fusiondirectory-setup line 585.
.........
** [fusiondirectory] Fusiondirectory 1.3 initialized and ready to login

**Comment by tiredofit** [comment]
Alright. Let me spin up a local copy here and see whats happening. It's been a while since I have done a new build and some could be related to either the new base image (likely) or their source tree (just as likey). I'll need an hour and a half.

**Comment by tiredofit** [comment]
Alright, that is embarrassing. I'm building `2.0.1` and `latest` and also reverting back to PHP 7.2 as am seeing some warnings that need to be dealt with upstream. Cause is that I wasn't calling a variable properly. Tested on our Dev system and functioning as expected.

**Comment by Anganthier** [comment]
Just tested it, seems to work now. Plugins are working.
