### ISSUE TITLE
Link to  openldap-fusiondirectory not working

### ISSUE THREAD

**Issue by tobiasbp** [tiredofit/docker-fusiondirectory#2]
In the Prerequisites section of the link to "the accompanying openldap-fusiondirectory image" does not work.

**Comment by tiredofit** [comment]
Hi Tobias, 
It appears I haven't put my sourcecode up for the openldap-fusiondirectory image. I'll spend some time to make it sanitized for public usage and repond back here when completed.

**Comment by tiredofit** [comment]
After a long delay you can find the new image at https://github.com/tiredofit/docker-openldap-fusiondirectory
