### ISSUE TITLE
[kubernetes] error neither LDAP2_ADMIN_PASS nor LDAP2_ADMIN_PASS_FILE are set but are required

### ISSUE THREAD

**Issue by mamiapatrick** [tiredofit/docker-fusiondirectory#24]
Hello,

I set an image of fusiondirectory and provide information fo my ldap server but i still got an error that there's missing parameter for the second LDAP server unlike i provide the LDAP_DEFAULT paramater as the LDA1_NAME and i only have 1 LDAP server

**Comment by mamiapatrick** [comment]
I'm on Kubernetes and when i try to debug i see that the command `printenv | sort | grep '^LDAP.*HOST' | wc -l` return two lines with
LDAP_HOST=openldap-fusiondirectory
LDAP_SERVICE_HOST=10.43.55.127

Where the second one is the ip of the service

**Comment by tiredofit** [comment]
Not sure what LDAP_SERVICE_HOST is.. thats not a part of this image.. I'll need full logs to begin to troubleshoot.

**Comment by mamiapatrick** [comment]
Hello i solved this issues. This was related to another kubernetes deployment which was named ldap so his service has a variable named ldap_service_host with the value of the IP of the service. I just need to rename this to correct this. But for me I think that raise a feature request about change the algorithm to detect the number of ldap host. Maybe a better regex for that. Thanks

**Comment by bmalynovytch** [comment]
This one needs to be reopened, I just fell on it.
Digging to understand how to fix it here.
