### ISSUE TITLE
nginx doesn't seem to be serving any pages

### ISSUE THREAD

**Issue by hxvxt2** [tiredofit/docker-fusiondirectory#30]
Hello Guys,

I ran a fresh image via `docker-compose up` but noticed the nginx server wasn't running. I followed the suggestions from `nginx -t` made some change and somehow got it working.

So after making the changes, I ran a `ngnix -t` once again, here is the output:
```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

Everthing looks fine. So I treid `curl -i localhost:80` but this fails with:

```

> HTTP/1.1 502 Bad Gateway
> Server: nginx/1.17.10
> Date: Tue, 21 Apr 2020 14:49:12 GMT
> Content-Type: text/html
> Content-Length: 158
> Connection: keep-alive
> <html>
> <head><title>502 Bad Gateway</title></head>
> <body>
> <center><h-1>502 Bad Gateway</h-1></center>
> <hr><center>nginx/1.17.10</center>
> </body>
> </html>

```

I have attached my `nginx.conf`. I also see a `default.conf` in `/etc/nginx/conf.d/` which contains a **"server"** context. Should I add this block into my **"html"** context in `nginx.conf`

Any direct help or suggestions in the right direction will help. 

Regards
-Vikrant

**Comment by tiredofit** [comment]
Hi there - 502 Bad Gateway usually means that it's a problem with the PHP Engine. Can you get me full logs of your container startup and email to dave at tiredofit dot ca ?

**Comment by hxvxt2** [comment]
Thanks @tiredofit 

I sent you an email with the logs.

**Comment by hxvxt2** [comment]
Thanks @tiredofit 

The latest image worked without any issues.
