### ISSUE TITLE
Nextcloud plugin not usable

### ISSUE THREAD

**Issue by mjmucha** [tiredofit/docker-fusiondirectory#33]
I tried to use the new Nextcloud plugin. But when i access the Nextcloud page inside FusionDirectory i get the following error:

```
Plugin
Fatal error: Cannot find any plugin definitions for plugin '?plug=64' ('..//plugins/personal/nextcloud/main.inc' is not a file)!

Please fix the above error and reload the page.
```

I did fix this for my instance by manually mounting a `main.inc` file to `/www/fusiondirectory/plugins/personal/nextcloud/` with the content:
```
<?php
nextcloudAccount::mainInc('nextcloudAccount', $ui->dn);
?>
```

**Comment by tiredofit** [comment]
Hi there, to look into to see if I've missed something from installing. Will have a solution within 24 hours.

**Comment by tiredofit** [comment]
Thanks, I've looked into it and it seems the upstream source is missing the file. I've built in a workaround in the code.

Tagged as `tiredofit/fusiondirectory:latest` and `tiredofit/fusiondirectory:2.5.1`

**Comment by joergmschulz** [comment]
on startup, I see
`/var/run/s6/etc/cont-init.d/40-fusiondirectory: line 54: /www/fusiondirectory/plugins/personal/nextcloud/main.inc: No such file or directory`
nevertheless; used the current image and alternatively cloned and built it myself.
But, it is possible to add nextcloud attributes to people. Only on trying to review my own nextcloud attributes, the error shows up again.

**Comment by tiredofit** [comment]
Got it. Installing the main.inc in a staging area instead of directly to the path, as it's failing due to the way fusiondirectory plugins are installed. Tagged as `tiredofit/fusiondirectory:latest` and `tiredofit/fusiondirectory:2.5.2`

**Comment by joergmschulz** [comment]
confirmed - this works.

**Comment by mjmucha** [comment]
Sure! I only had time today to look into it. For me it is also fixed
